[package]
name = "shape_mapper"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shape_mapper"
path = "source/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
